name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cgo_enabled: 0
          - os: windows-latest
            cgo_enabled: 1
          - os: macos-latest
            cgo_enabled: 1
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v github.com/pqsec/passkb/cmd/passkb
      env:
        CGO_ENABLED: ${{ matrix.cgo_enabled }}

    - name: Test
      run: go test -v .
